### ISSUE TITLE
“About” text

### ISSUE THREAD

**Issue by Dev1an** [Eucharistie/streaming-links#11]
Add basic intro text describing the website and/or an about page (#2). Can be copied (#5) from WordPress.

**Comment by jaskedf** [comment]
Beste bezoeker,

Welkom op eucharistie.info, dé plaats waar informatie over eucharistievieringen in Vlaanderen verzameld en gebundeld wordt.

In tijden van coronavirus zijn we genoodzaakt om ons geloof te beleven door gebruik te maken van hedendaagse technologieën. Heel wat priesters en parochies delen vieringen en gebedsmomenten via het internet, door middel van “videostreams”. De komende weken zullen we dus proberen om zo veel mogelijk informatie over de verschillende live videostreams met u te delen.

In de sectie Missaal vind je meer info over waar je lezingen en andere liturgische teksten kan terugvinden.

Heb je zelf nuttige informatie die je graag wil delen met de gelovige gemeenschap? Laat je gegevens achter via het contactformulier.

**Comment by duvrai** [comment]
Heb je zelf nuttige informatie die je graag wil delen met de gelovige gemeenschap? ~~Laat je gegevens achter via het contactformulier.~~ Stuur ons een [mailtje](mailto:contact@eucharistie.info). 

OK? Da's misschien voor een volgende versie ...
