### ISSUE TITLE
Update logo and colors

### ISSUE THREAD

**Issue by Dev1an** [Eucharistie/streaming-links#12]
Please share a vector version of the logo so that we can use the same one everywhere (website, YouTube, Facebook, ...)

**Comment by duvrai** [comment]
blauw=#438DCC
groen=#2BA83D

**Comment by duvrai** [comment]
Looks okay after 2e926e3788f7368adf5bd5ec6be237162bcb45f1, 1126157dc98cbcc5083daf70729a3846d8c540ae, d59fef94dd475aeee4b8d40a14d28ad4d548744f and 6df443f1f6639e999e6539f559478b0eb69e556e
