### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by Dev1an** [Eucharistie/streaming-links#15]
Would be good to log user behaviour.
For example summary of the clicks to all websites
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/3158324/77290773-2a365f00-6cdd-11ea-8e79-0d2ccc8a553e.png">
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/3158324/77290794-37534e00-6cdd-11ea-8713-efd95b1d2f28.png">

**Comment by duvrai** [comment]
Can we not use GA?

**Comment by Dev1an** [comment]
Yes we can. But we will have to include a tracking tag then. It would be good to add this before we go live.

**Comment by Dev1an** [comment]
Sorry misunderstood @duvrai's question. Because he does not want to store and share our tracking data with Google, we will store it in our own database at Combell.

Stats can be retrieved using [stats.dpro.be](https://stats.dpro.be)

**Comment by Dev1an** [comment]
![image](https://user-images.githubusercontent.com/3158324/77528463-4a595000-6e8e-11ea-881c-7e41487ef208.png)
