### ISSUE TITLE
Create temporary banner to inform vistors of the transition from Wordpress to GitHub

### ISSUE THREAD

**Issue by jaskedf** [Eucharistie/streaming-links#18]
Om de steeds groter wordende informatiestroom overzichtelijk weer te geven, hebben we de voorbije dagen hard gewerkt aan een compleet nieuwe site. Deze zal ons in de toekomst ook de mogelijkheid geven om informatie beter te doorzoeken en te filteren. Heb je vragen of suggesties? Laat het weten aan de webmaster (link mailto:webmaster@eucharistie.info)

**Comment by duvrai** [comment]
Ok this fixes #6 😉

**Comment by Dev1an** [comment]
webmaster@eucharistie.info bestaat niet

**Comment by duvrai** [comment]
contact@eucharistie.info ?

**Comment by Dev1an** [comment]
Ja das het juiste. Eigenlijk zouden we alle adressen moeten forwarden naar dat adres. (Soort van catch all address)
