### ISSUE TITLE
Should we transfer hosting to netlify?

### ISSUE THREAD

**Issue by Dev1an** [Eucharistie/streaming-links#20]
**Advantage 👍**
Gives us the ability to add simple contact form. #4

**Disadvantage 👎**
Only one management account in free plan. For extra team members $15/user.

**Comment by duvrai** [comment]
What kind of management are we talking about ?

**Comment by Dev1an** [comment]
@duvrai See https://github.com/Eucharistie/streaming-links/issues/4#issuecomment-603804971

**Comment by Dev1an** [comment]
So management of deploys, forms, and optionally functions if we would use functions in the future.

**Comment by Dev1an** [comment]
We transitioned to Netlify. Contact form is not yet added.
