### ISSUE TITLE
A good new title?

### ISSUE THREAD

**Issue by duvrai** [Eucharistie/streaming-links#38]
Discuteer eerst over een goede titel, doe dan een nieuwe request.

_Originally posted by @Dev1an in https://github.com/Eucharistie/streaming-links/pull/25#issuecomment-605524330_

**Comment by duvrai** [comment]
So @jaskedf wants "Eucharistievieringen in Vlaanderen". I think that would be cool as an initiative in itself, but the website is already growing beyond that (unless you have a [loose definition of Flanders](https://nl.wikipedia.org/wiki/Vlaanderen_Vakantieland))), even though we are not yet giving editing access to outsiders.

### Proposed solution
- We make a flemish *part* of the site (currently the only part). We only include channels that are truly accessible to all flemish people. This would mean either dutch speaking or dutch subtitled/translated content. We are open to the possibility of adding whole-site translations for communities in other languages, these would exist in another directory next to the flemish one. For example:  
  - eucharistie.info/nl
  - eucharistie.info/fr

**Comment by Dev1an** [comment]
Internationalising the whole site is a nice idea but seems like a major update to me (V3 or V4?).

**Comment by jaskedf** [comment]
There are already plenty of international options. We don't have the workforce nor the content to provide global information on our website. This is the reason why, with the initiative of eucharistie.info, we want to focus on Flanders.
New proposal for Title: "Eucharistie-info voor Vlaanderen". This title has a clear link between the domain name and the goal of the initiative.
For non-flemish content currently on the website, we can create a separate page or temporarily disable/remove it.
It is important to keep watch of the intention of this initiative: Gather information of eucharistic celebrations in Flanders.
I already received a lot of feedback on the website, all of them come from flemish speaking people, not a single one was in another language. This is an indication and motivation to stay loyal to the original scope.

**Comment by duvrai** [comment]
Eucharistie is a french word adopted in the Flemish language.

**Comment by duvrai** [comment]
Do we need to disable the channels in other languages? I created the language filter to let the user do that. I will change the title.

**Comment by dRomke** [comment]
I agree with @jaskedf. Currently the main scope is Flanders but slightly crossing the borders (eg. Bxl) or other languages (English, Latin) should be acceptable, just like what people do in non-corona times to find what fits them best.

I don’t think splitting the site is a good idea as it makes it needlessly complex for people who don’t care about what language to listen to.
Unless a French/other speaking admin team pops up it is out of scope to support this broader community.
