### ISSUE TITLE
Nieuwe uren voor Ieper: Sint-Maartenskathedraal

### ISSUE THREAD

**Issue by Dev1an** [Eucharistie/streaming-links#64]
@d0rable: Nieuwe uurtjes om aan te passen 😀

FROM: Mathias Parret <mathiasparret@hotmail.com>

> Beste,
>  
> Langs deze weg laat ik je weten dat de livestream zaterdagavondvieringen vanuit de Sint-Maartenskathedraal van Ieper voortaan wekelijks wordt uitgezonden op zaterdag om 17.30 u. (i.p.v. 17.00 u.) (liturgie van de zondag)
>  
> Dank om dit te willen aanpassen op de website.
>  
> Met vriendelijke groeten,
>  
> Pr. Mathias Parret
> Pastorale Eenheid O.L.V. van Vrede Ieper
> Janseniusstraat 3
> B-8900 Ieper
> mathias.parret@kerkinieper.be
> www.kerkinieper.be
> tel: 057/367.588
> gsm: 0499/355.334

**Comment by d0rable** [comment]
time updated
