### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by d0rable** [Eucharistie/streaming-links#69]
filter for languages on the uurrooster page is not showing any options

**Comment by Dev1an** [comment]
Euhm @d0rable, ik had dit juist aan @duvrai gevraagd

**Comment by d0rable** [comment]
sorry dacht dat ik dat per ongeluk had toegevoegd, dus had het terug weggedaan

**Comment by duvrai** [comment]
hallo hier ben ik weer 😊

**Comment by duvrai** [comment]
Fixed in 20c80f0.

**Comment by duvrai** [comment]
Oei, als je op een andere dag dan vandaag staat, toont de filter toch de items van vandaag. #70

**Comment by duvrai** [comment]
Fixed in eb52577.

**Comment by Dev1an** [comment]
Mag ik dat dan mergen?
