### ISSUE TITLE
New community in Gistel: Moeder van Vrede

### ISSUE THREAD

**Issue by Dev1an** [Eucharistie/streaming-links#80]
Beste,

Om 10u op zondag kan men de H mis meevieren vanuit de abdijkerk te Gistel bij de gemeenschap 'Moeder van Vrede'

Via hun website of youtube kanaal.

Mvg
Steven Hosten

**Comment by Dev1an** [comment]
@jaskedf kanaal is toegevoegd. Je mag een antwoord sturen naar Steven

**Comment by jaskedf** [comment]
Bedankt! Mail gestuurd.
